### ISSUE TITLE
Attempts to load 95k server chunks 

### ISSUE THREAD

**Issue by MLMII** [inayakitori/4dmc#13]
Looking at the F3 screen it claims my single player game is attempting to load 95K "server chunks" which causes my single player game to 'hang' but not actually crash.

**Comment by inayakitori** [comment]
A few questions:
- Is this in singleplayer or are you running this on a server?
- What is your current render distance set to? 95,000 chunks seems to be about a render distance of around 32, which would crash your game cause the chunk loading scales cubicly, that'd be equivalent to a 3D render distance of ~150.
- Are you using any other mods with this one?

**Comment by inayakitori** [comment]
Upon further inspection, I've also found that the server chunk rendering is unreasonably high, I'll try to see what the issue is

**Comment by inayakitori** [comment]
Looking at the difference in chunk loading in [this empirical test](https://www.desmos.com/calculator/foy2lxuidj) I think this is an expected consequence of the 4D chunk propagation; The server actual does need to cache all those chunks. A temporary fix would be to lower the render distance but I'll also try to [limit 4D chunk loading](#15) in a future release
