### ISSUE TITLE
Make flowing liquids flow between slices

### ISSUE THREAD

**Issue by Mysticpasta1** [inayakitori/4dmc#20]
Making flowing liquids like lava and water flow between slices so you can have water falls that appear from nowhere in 1 slice and in another one it is the water source block it comes from.

Water would flow X, Y, Z, and W.

**Comment by CreepyCre** [comment]
implemented by df40a4d93647c2cfad06e9b4d6a88fc892f1b43e & 6951877ba4a9afce5902afc5a14cb703fa2751e0
