### ISSUE TITLE
Do you want help with coding this.

### ISSUE THREAD

**Issue by Mysticpasta1** [inayakitori/4dmc#21]
I would love to help code on this project, I already made a fork.
My curseforge profile is Mysticpasta1
My discord is HauntedPasta1#8200, DM me pls

**Comment by inayakitori** [comment]
If you wanna contribute I've started work on a redstone update so if you want to maybe make a pull request for #20 and then I'll add you to the project?

**Comment by Mysticpasta1** [comment]
sure thing also I went and backported it to 1.18.2 fabric because I wanted to test it with something on that version, I have it on github but I need a 1.18.2-Forge-Redstone branch on this github to PR it

**Comment by Mysticpasta1** [comment]
btw I have been talking about your mod in this discord server for a good while today if you want to join in the conversation https://discord.gg/tYpQMTa
