### ISSUE TITLE
4D screenshots

### ISSUE THREAD

**Issue by inayakitori** [inayakitori/4dmc#31]
Maybe placing [placeW] + [screenshot] should put the player in "screenshot mode". This locks the player's look position and 3D position. The player can then choose to either start stepping kata or ana. If the player steps ana first, they can then press [screenshot] and then step ana again and repeat the process. This stops the player from being allowed to step kata, similar to how in a panorama you keep on stepping in one direction. then when the player presses [placeW] + [screenshot] again the screenshots are composed into a singular image and saved to the player's screenshot folder

**Comment by Nageek15** [comment]
An option to compile the images into a low framerate gif

**Comment by inayakitori** [comment]
> An option to compile the images into a low framerate gif

We could implement this with a config option for what type of screenshot4 to take:
vertical
horizontal (cursed)
grid (left to right top to bottom)
snake
hilbert
GIF

**Comment by Frisk-256** [comment]
i was thinking there would be a menu to chose a start and end w coordinate and it would come out gif going through every w slice between them
