### ISSUE TITLE
[BUG] Crash when trying to place stair along ana/kata

### ISSUE THREAD

**Issue by SalTeyJek004** [inayakitori/4dmc#36]
i tried placing a birch stair along ana and my game crashed

Minecraft version: 1.20.2
Mod version: 0.2.4dev2
Other Mods:
--Immersive Portals 4.1.0
--Mod Menu 8.0.0
--Pehkui 3.7.11
--Sodium 0.5.3
--Gravity Changer (Qouteall fork) 0.90.7
![image](https://github.com/inayakitori/4dmc/assets/53840187/230a451f-0156-40bb-afb5-1216c5e7b203)

**Comment by Coolcatt5000** [comment]
I noticed this issue with doors and gates as well
