### ISSUE TITLE
[BUG] Using a debug stick on an ana/kata facing observer freezes the game

### ISSUE THREAD

**Issue by samhaygood05** [inayakitori/4dmc#40]
I right clicked on a kata facing observer with a debug stick and the game stopped ticking

Minecraft version: 1.20.2
Mod version: 0.2.4dev2
Other Mods:
--Mod Menu 8.0.1
--Sodium 0.5.5

**Comment by inayakitori** [comment]
resolved in 0d08f72a2f7970edf53ca909cfc281674d7626c7
