### ISSUE TITLE
(suggestion) make the player choose how much of the other worlds to load

### ISSUE THREAD

**Issue by krispyking24** [inayakitori/4dmc#41]
this might save on some memory but take this with a grain of salt as i haven't yet played with the mod yet this is just based on one of the change logs said something about increasing memory usage

**Comment by krispyking24** [comment]
idk about others but i wouldn't think most people would want to go up or down more than like 4 worlds but have an opinion in the config to chose how many worlds up or down they want to generate as currently at least for me on the first generation of a world it's taken more then 10 minutes at 0% loaded

**Comment by inayakitori** [comment]
What's your initial simulation distance? that can make world loading slower too. 

> 10 minutes at 0% loaded

Did that world just never load? that might be a different issue then to do with some worlds just not loading

**Comment by krispyking24** [comment]
soon after making that comment the game crashed so i'm trying to load it up again, my sim distance is 4 iirc

**Comment by inayakitori** [comment]
any updates on this? If you're having issues with render distance than decrease your render distance

**Comment by krispyking24** [comment]
in the end i just want with the different instance
