### ISSUE TITLE
A setting that allows you to see your w coordinate

### ISSUE THREAD

**Issue by Fireball15606** [inayakitori/4dmc#45]
It would show the w coordinate in the corner as its annoying that I have to keep going to the f3 menu

**Comment by Frisk-256** [comment]
this is an amazing idea

**Comment by Frisk-256** [comment]
i have made a gui in desmos graphing calculator
https://www.desmos.com/calculator/sdvgeyojta

**Comment by inayakitori** [comment]
Made in 2c14c82390219726f22a9734571a81cdf1c760fa
