### ISSUE TITLE
Client only loads current world slice

### ISSUE THREAD

**Issue by Frisk-256** [inayakitori/4dmc#50]
possibly 1 or 2 W slices could be loaded around the player so when you change your slice, the chunks do not have to load because they are already loaded, so it is completely seamless if you do not move through slices faster that chunk loading. the render distance could be smaller in the nearby slices so it does not lag to much while still being seamless for nearby objects even if their are loading chunks at the edge of your render distance.

**Comment by inayakitori** [comment]
Why isn't decreasing render distance a fix for this?

**Comment by Frisk-256** [comment]
lowing the render distance to 0 would, even with a small render distance, the chunks still need to load, and that makes the world flash for less than a second, which is still noticeable. if you loaded even just the 2 ajacent slices would make the transition between dimensions would be seamless and would look a lot better. how about you can control how many slices away chunks are loaded, and 0 would turn this off so like up to 5 blocks W. like a setting in the video settings

**Comment by inayakitori** [comment]
What you're observing here is an issue but the reasoning is wrong. The client only receives the chunks that are in its slice, only the server loads chunks 4Dly. What you're asking for is a way for the client to receive chunk packets for chunks that aren't in its own slice.
This isn't an easy issue so I'm not going to work on it right now but its definitely something I want to fix in the future

**Comment by inayakitori** [comment]
Fixed in [cb51f8c](https://github.com/inayakitori/4dmc/commit/cb51f8cf2106d777f74d795ac1cb74ea3d28668d)
