### ISSUE TITLE
gamerule spawnRadius

### ISSUE THREAD

**Issue by iluha168** [inayakitori/4dmc#53]
Currently gamerule `spawnRadius` does not affect the 4th coordinate at all - you always spawn at W = 0.

**Comment by inayakitori** [comment]
I think creating a gamerule is unnecessary complexity so I'm going to just spread out the spawn +- 5 slices

**Comment by iluha168** [comment]
This is a vanilla game rule. It already exists, it just has no effect on 4th dimension.

**Comment by inayakitori** [comment]
ok I see that now. I will simply make it spread out the player by a constant factor * the spawn radius (1/2, 1/4, whatever feels right. w movement is more "costly" than xz movement so it feels wrong to spread the players out too much
