### ISSUE TITLE
4D Rotation

### ISSUE THREAD

**Issue by Enator18** [inayakitori/4dmc#62]
A feature that I think would greatly enhance this mod would be the ability to rotate in 4D. What I mean by this is you could rotate so instead of viewing an xyz cross section and being able to scroll along the w axis, you could rotate so that the 3d space you are viewing is the xyw plane, and the scroll keybinds would move you along z instead. I don't know if this would even be possible with the way that this is implemented. It would likely require some infrastructural changes, however if it could be done, it would breath so much life into the 4D environment and help make it feel truly 4D. It would make building 4D redstone contraptions much easier.

**Comment by inayakitori** [comment]
It is interesting but not something I am interested in implementing. I will not be working towards making this possible any time soon. It is too much work for me and my skills are not there. I understand it would be very cool but there's so much more that has to happen before this is even viable and also (again) it might never happen.

**Comment by Enator18** [comment]
Yeah, that makes sense, it would be very difficult to implement. I will say this mod is super awesome and I look forward to making really cool contraptions in it, especially once I have ana/kata pistons.

**Comment by inayakitori** [comment]
> ...especially once I have ana/kata pistons.
They're actually in the newest beta release!
