### ISSUE TITLE
Layer Unlocker or such

### ISSUE THREAD

**Issue by The-Final-Empire-Of-Dogs** [inayakitori/4dmc#71]
So my thought would be that once the mod is stable enugh to run in survival that maybe there could be a "layer swaper" type item that can have a creative variant that unlocks everything but it would mean that a survival player can use it to unlock up to a certan layer. so for example to start you can only use 1 layer but then you could craft the first one and unlock -1 and 1, and then the second would be -2 and 2, etc. maybe chests and ores would then not spawn in layers asie from the base one.

**Comment by inayakitori** [comment]
This seems like a variation on world generation that would exist as it's own mod/datapack. As such, it will not be included in the mod.

The idea of having certain things only far away from the origin slice W=0 is interesting and I might do something based off that.
